spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # Configuration Cloud et Discovery
  cloud:
    discovery:
      enabled: true

  security:
    oauth2:
      resource server:
        jwt:
          # L'URL de ton Realm Keycloak
          issuer-uri: http://localhost:8180/realms/ticketflow

          # URL pour récupérer les clés publiques de signature (JWK)
          jwk-set-uri: http://localhost:8180/realms/ticketflow/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

keycloak:
  server-url: http://localhost:8180
  realm: ticketflow # Ou ton realm spécifique
  client-id: user-service
  username: admin
  password: admin

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: DEBUG

eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka # En local sans docker
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
      # defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka/} # A utiiser en demarrant avec Docker

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        # On expose uniquement le nécessaire pour la santé et le diagnostic de base
        include: health, info
  endpoint:
    health:
      # Affiche les détails (db, diskSpace, etc.) pour comprendre l'origine d'une panne
      show-details: always
      # Optionnel : permet de grouper les indicateurs
      probes:
        enabled: true

#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    enabled: false # On le désactive ici car on veut uniquement celui de la Gateway

    ## C'est pour la dependance Actuator
    #management:
    #  endpoint:
    #    web:
    #      exposure:
    #        include: *

    # # Pour tester si ca tourne => http://localhost:8888/application/default (ui)