spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # Configuration Cloud et Discovery
  cloud:
    discovery:
      enabled: true

  security:
    oauth2:
      resource server:
        jwt:
          # L'URL de ton Realm Keycloak
          issuer-uri: http://localhost:8180/realms/ticketflow

          # URL pour récupérer les clés publiques de signature (JWK)
          jwk-set-uri: http://localhost:8180/realms/ticketflow/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

keycloak:
  server-url: http://localhost:8180
  realm: ticketflow # Ou ton realm spécifique
  client-id: user-service
  username: admin
  password: admin

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    enabled: false # On le désactive ici car on veut uniquement celui de la Gateway

    ## C'est pour la dependance Actuator
    #management:
    #  endpoint:
    #    web:
    #      exposure:
    #        include: *

    # # Pour tester si ca tourne => http://localhost:8888/application/default (ui)