global:
  params:
    p1: 20
    p2: 20

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # Configuration Cloud et Discovery
  cloud:
    discovery:
      enabled: true

  security:
    oauth2:
      resource server:
        jwt:
          # L'URL de ton Realm Keycloak
          issuer-uri: http://localhost:8180/realms/ticketflow

          # URL pour récupérer les clés publiques de signature (JWK)
          jwk-set-uri: http://localhost:8180/realms/ticketflow/protocol/openid-connect/certs

keycloak:
  server-url: http://localhost:8180
  realm: ticketflow # Ou ton realm spécifique
  client-id: user-service
  username: admin
  password: admin

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

    ## C'est pour la dependance Actuator
    #management:
    #  endpoint:
    #    web:
    #      exposure:
    #        include: *

    # # Pour tester si ca tourne => http://localhost:8888/application/default (ui)