spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/document_db
    username: postgres
    password: admin
    # password: Pa$$w0rd!
    # driver-class-name: org.postgresql.Driver

  data:
    rest:
      base-path: /api/v1