########## start => Config postgresql ##########
spring:
  datasource:
    # url: jdbc:postgresql://localhost:5432/notification_db
    url: jdbc:postgresql://postgres-notification:5436/notification_db
    username: postgres
    password: admin
    # password: Pa$$w0rd!
    # driver-class-name: org.postgresql.Driver

  data:
    rest:
      base-path: /api