########## start => Config postgresql ##########
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_db
    # url: jdbc:postgresql://postgres-ticket:5435/ticket_db
    username: postgres
    password: admin
    # password: Pa$$w0rd!
    # driver-class-name: org.postgresql.Driver

  data:
    rest:
      base-path: /api
